import os
from typing import Dict

import openai

# read API key once at import time; useful for environments where
# the key may be configured in advance.
api_key = os.getenv("OPENAI_API_KEY")


def generate_ai_summary(metrics: Dict, sql_insights: Dict, validation_summary: Dict) -> str:
    """Builds a prompt from provided statistics and sends it to an OpenAI LLM.

    The returned text is intended for senior leadership and contains an
    overview of data integrity, risks, operational impact, and advice on
    remediation priorities.

    Args:
        metrics: Dictionary containing high-level metrics such as
            ``total_records`` and ``invalid_pct`` (percentage of invalid
            entries).
        sql_insights: Dictionary with derived SQL insights such as
            ``duplicate_sku_count``, ``high_price_anomalies`` and
            ``low_inventory_warnings``.
        validation_summary: Dictionary containing validation results like
            ``top_issue_types`` (a list or comma-separated string).

    Returns:
        A single paragraph summary generated by the LLM.
    """

    # gather values with sensible defaults when missing
    total_records = metrics.get("total_records", "unknown")
    invalid_pct = metrics.get("invalid_pct", "unknown")
    top_issues = validation_summary.get("top_issue_types", "none reported")
    duplicate_sku = sql_insights.get("duplicate_sku_count", 0)
    high_price = sql_insights.get("high_price_anomalies", 0)
    low_inv = sql_insights.get("low_inventory_warnings", 0)

    prompt = (
        "You are an executive-level business analyst. "
        "Based on the following dataset metadata, prepare a concise, "
        "professional paragraph suitable for senior leadership:\n\n"
        f"- Total records: {total_records}\n"
        f"- Invalid record percentage: {invalid_pct}%\n"
        f"- Top issue types: {top_issues}\n"
        f"- Duplicate SKU count: {duplicate_sku}\n"
        f"- High price anomalies: {high_price}\n"
        f"- Low inventory warnings: {low_inv}\n\n"
        "Your summary should address overall data integrity, primary risk "
        "drivers, operational impact, and suggested remediation focus areas. "
        "Keep the tone appropriate for a senior leadership audience."
    )

    # ensure we have an API key (module-level value may already exist)
    key = api_key or os.getenv("OPENAI_API_KEY")
    if not key:
        raise RuntimeError("OPENAI_API_KEY is not set in the environment")

    openai.api_key = key

    # make the request; low temperature for consistent output
    resp = openai.ChatCompletion.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=250,
    )

    # extract and return text; the SDK may return a dict or a custom object
    if isinstance(resp, dict):
        choices = resp.get("choices", [])
    else:
        choices = getattr(resp, "choices", [])

    if not choices:
        raise RuntimeError("No completion choices returned from OpenAI")

    # choices[0] may also be object/dict
    first = choices[0]
    if isinstance(first, dict):
        content = first["message"]["content"]
    else:
        content = first.message["content"]

    return content.strip()
